openapi: "3.0.0"
info:
  title: "Bee Travels Hotel V1 Service"
  version: "1.0.0"
  description: "replace this with a real description of your service"
  license:
    name: "Apache 2.0"
    url: "https://github.com/bee-travels/bee-travels-node/blob/master/LICENSE"
